// Code generated by protoc-gen-go. DO NOT EDIT.
// source: car.proto

package grpcproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterTripRequest struct {
	BeginLeaveTime       int64    `protobuf:"varint,1,opt,name=beginLeaveTime,proto3" json:"beginLeaveTime,omitempty"`
	EndLeaveTime         int64    `protobuf:"varint,2,opt,name=endLeaveTime,proto3" json:"endLeaveTime,omitempty"`
	From                 *Point   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Point   `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterTripRequest) Reset()         { *m = RegisterTripRequest{} }
func (m *RegisterTripRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterTripRequest) ProtoMessage()    {}
func (*RegisterTripRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_car_f71d6927a9eef854, []int{0}
}
func (m *RegisterTripRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterTripRequest.Unmarshal(m, b)
}
func (m *RegisterTripRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterTripRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterTripRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterTripRequest.Merge(dst, src)
}
func (m *RegisterTripRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterTripRequest.Size(m)
}
func (m *RegisterTripRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterTripRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterTripRequest proto.InternalMessageInfo

func (m *RegisterTripRequest) GetBeginLeaveTime() int64 {
	if m != nil {
		return m.BeginLeaveTime
	}
	return 0
}

func (m *RegisterTripRequest) GetEndLeaveTime() int64 {
	if m != nil {
		return m.EndLeaveTime
	}
	return 0
}

func (m *RegisterTripRequest) GetFrom() *Point {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *RegisterTripRequest) GetTo() *Point {
	if m != nil {
		return m.To
	}
	return nil
}

type FindTripRequest struct {
	BeginLeaveTime       int64    `protobuf:"varint,1,opt,name=beginLeaveTime,proto3" json:"beginLeaveTime,omitempty"`
	EndLeaveTime         int64    `protobuf:"varint,2,opt,name=endLeaveTime,proto3" json:"endLeaveTime,omitempty"`
	From                 *Point   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Point   `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Option               int32    `protobuf:"varint,5,opt,name=option,proto3" json:"option,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindTripRequest) Reset()         { *m = FindTripRequest{} }
func (m *FindTripRequest) String() string { return proto.CompactTextString(m) }
func (*FindTripRequest) ProtoMessage()    {}
func (*FindTripRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_car_f71d6927a9eef854, []int{1}
}
func (m *FindTripRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindTripRequest.Unmarshal(m, b)
}
func (m *FindTripRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindTripRequest.Marshal(b, m, deterministic)
}
func (dst *FindTripRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindTripRequest.Merge(dst, src)
}
func (m *FindTripRequest) XXX_Size() int {
	return xxx_messageInfo_FindTripRequest.Size(m)
}
func (m *FindTripRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindTripRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindTripRequest proto.InternalMessageInfo

func (m *FindTripRequest) GetBeginLeaveTime() int64 {
	if m != nil {
		return m.BeginLeaveTime
	}
	return 0
}

func (m *FindTripRequest) GetEndLeaveTime() int64 {
	if m != nil {
		return m.EndLeaveTime
	}
	return 0
}

func (m *FindTripRequest) GetFrom() *Point {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *FindTripRequest) GetTo() *Point {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *FindTripRequest) GetOption() int32 {
	if m != nil {
		return m.Option
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterTripRequest)(nil), "grpcproto.registerTripRequest")
	proto.RegisterType((*FindTripRequest)(nil), "grpcproto.findTripRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CarClient is the client API for Car service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CarClient interface {
	// driver
	RegisterTrip(ctx context.Context, in *RegisterTripRequest, opts ...grpc.CallOption) (*Bool, error)
	// user
	FindTrip(ctx context.Context, in *FindTripRequest, opts ...grpc.CallOption) (*JsonResponse, error)
}

type carClient struct {
	cc *grpc.ClientConn
}

func NewCarClient(cc *grpc.ClientConn) CarClient {
	return &carClient{cc}
}

func (c *carClient) RegisterTrip(ctx context.Context, in *RegisterTripRequest, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/grpcproto.car/registerTrip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carClient) FindTrip(ctx context.Context, in *FindTripRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, "/grpcproto.car/findTrip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarServer is the server API for Car service.
type CarServer interface {
	// driver
	RegisterTrip(context.Context, *RegisterTripRequest) (*Bool, error)
	// user
	FindTrip(context.Context, *FindTripRequest) (*JsonResponse, error)
}

func RegisterCarServer(s *grpc.Server, srv CarServer) {
	s.RegisterService(&_Car_serviceDesc, srv)
}

func _Car_RegisterTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarServer).RegisterTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcproto.car/RegisterTrip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarServer).RegisterTrip(ctx, req.(*RegisterTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Car_FindTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarServer).FindTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcproto.car/FindTrip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarServer).FindTrip(ctx, req.(*FindTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Car_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcproto.car",
	HandlerType: (*CarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "registerTrip",
			Handler:    _Car_RegisterTrip_Handler,
		},
		{
			MethodName: "findTrip",
			Handler:    _Car_FindTrip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "car.proto",
}

func init() { proto.RegisterFile("car.proto", fileDescriptor_car_f71d6927a9eef854) }

var fileDescriptor_car_f71d6927a9eef854 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x91, 0x5d, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x99, 0xa4, 0x2d, 0xf6, 0x1a, 0x5a, 0xb9, 0x82, 0x86, 0x3c, 0x48, 0x08, 0x22, 0x79,
	0xca, 0x43, 0x5d, 0x40, 0x37, 0xe0, 0xd3, 0xd0, 0x0d, 0x24, 0xe9, 0x6d, 0x18, 0x71, 0xe6, 0x8e,
	0x33, 0xa3, 0xe0, 0x0a, 0x5c, 0x8b, 0x8b, 0x70, 0x6f, 0x42, 0xea, 0xcf, 0x58, 0xf4, 0xbd, 0x6f,
	0x73, 0xce, 0x77, 0x18, 0x0e, 0xe7, 0xc2, 0xbc, 0x6f, 0x5d, 0x63, 0x1d, 0x07, 0xc6, 0xf9, 0xe0,
	0x6c, 0x3f, 0x3e, 0x8b, 0xc5, 0x40, 0xac, 0x29, 0xb8, 0x97, 0x3d, 0x2a, 0xb2, 0x9e, 0xb5, 0x66,
	0xb3, 0x57, 0xd5, 0x9b, 0x80, 0x73, 0x47, 0x83, 0xf2, 0x81, 0xdc, 0xc6, 0x29, 0x2b, 0xe9, 0xf1,
	0x89, 0x7c, 0xc0, 0x1b, 0x58, 0x74, 0x34, 0x28, 0x73, 0x47, 0xed, 0x33, 0x6d, 0x94, 0xa6, 0x5c,
	0x94, 0xa2, 0x4e, 0xe5, 0x81, 0x8b, 0x15, 0x64, 0x64, 0xb6, 0x3f, 0xa9, 0x64, 0x4c, 0xfd, 0xf2,
	0xf0, 0x1a, 0x26, 0x3b, 0xc7, 0x3a, 0x4f, 0x4b, 0x51, 0x9f, 0xae, 0xce, 0x9a, 0xef, 0x6e, 0x8d,
	0x65, 0x65, 0x82, 0x1c, 0x29, 0x96, 0x90, 0x04, 0xce, 0x27, 0xff, 0x64, 0x92, 0xc0, 0xd5, 0xbb,
	0x80, 0xe5, 0x4e, 0x99, 0xed, 0x91, 0xf7, 0xc4, 0x0b, 0x98, 0xb1, 0x0d, 0x8a, 0x4d, 0x3e, 0x2d,
	0x45, 0x3d, 0x95, 0x9f, 0x6a, 0xf5, 0x2a, 0x20, 0xed, 0x5b, 0x87, 0x6b, 0xc8, 0xe2, 0xc9, 0xf1,
	0x2a, 0xfa, 0xe5, 0x8f, 0x5b, 0x14, 0xcb, 0x88, 0x77, 0xcc, 0x0f, 0xb8, 0x86, 0x93, 0xaf, 0x1d,
	0xb0, 0x88, 0xe0, 0xc1, 0x38, 0xc5, 0x65, 0xc4, 0xee, 0x3d, 0x1b, 0x49, 0xde, 0xb2, 0xf1, 0xd4,
	0xcd, 0x46, 0xef, 0xf6, 0x23, 0x00, 0x00, 0xff, 0xff, 0x78, 0x90, 0x77, 0x1b, 0x32, 0x02, 0x00,
	0x00,
}
