// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package grpcproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserProfile struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Avatar               string   `protobuf:"bytes,2,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	FullName             string   `protobuf:"bytes,4,opt,name=FullName,proto3" json:"FullName,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=Phone,proto3" json:"Phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProfile) Reset()         { *m = UserProfile{} }
func (m *UserProfile) String() string { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()    {}
func (*UserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_metadata_2bce8cdb0c060d9d, []int{0}
}
func (m *UserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfile.Unmarshal(m, b)
}
func (m *UserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfile.Marshal(b, m, deterministic)
}
func (dst *UserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfile.Merge(dst, src)
}
func (m *UserProfile) XXX_Size() int {
	return xxx_messageInfo_UserProfile.Size(m)
}
func (m *UserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfile proto.InternalMessageInfo

func (m *UserProfile) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserProfile) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserProfile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserProfile) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UserProfile) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func init() {
	proto.RegisterType((*UserProfile)(nil), "grpcproto.userProfile")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_metadata_2bce8cdb0c060d9d) }

var fileDescriptor_metadata_2bce8cdb0c060d9d = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x49,
	0x4c, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0x2f, 0x2a, 0x48,
	0x06, 0x33, 0x95, 0x5a, 0x19, 0xb9, 0xb8, 0x4b, 0x8b, 0x53, 0x8b, 0x02, 0x8a, 0xf2, 0xd3, 0x32,
	0x73, 0x52, 0x85, 0xc4, 0xb8, 0xd8, 0x42, 0x8b, 0x53, 0x8b, 0x3c, 0x5d, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0xa0, 0x3c, 0x90, 0xb8, 0x63, 0x59, 0x62, 0x49, 0x62, 0x91, 0x04, 0x13, 0x44,
	0x1c, 0xc2, 0x13, 0x12, 0xe1, 0x62, 0x75, 0xcd, 0x4d, 0xcc, 0xcc, 0x91, 0x60, 0x06, 0x0b, 0x43,
	0x38, 0x42, 0x52, 0x5c, 0x1c, 0x6e, 0xa5, 0x39, 0x39, 0x7e, 0x89, 0xb9, 0xa9, 0x12, 0x2c, 0x60,
	0x09, 0x38, 0x1f, 0xa4, 0x23, 0x20, 0x23, 0x3f, 0x2f, 0x55, 0x82, 0x15, 0xa2, 0x03, 0xcc, 0x49,
	0x62, 0x03, 0x3b, 0xc7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x0c, 0x21, 0x14, 0xab, 0x00,
	0x00, 0x00,
}
