// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notify.proto

package grpcproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NotifyMessage struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	CreatedTime          int64    `protobuf:"varint,2,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Image                string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Topic                string   `protobuf:"bytes,6,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyMessage) Reset()         { *m = NotifyMessage{} }
func (m *NotifyMessage) String() string { return proto.CompactTextString(m) }
func (*NotifyMessage) ProtoMessage()    {}
func (*NotifyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_notify_4ddc9a820ad42154, []int{0}
}
func (m *NotifyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyMessage.Unmarshal(m, b)
}
func (m *NotifyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyMessage.Marshal(b, m, deterministic)
}
func (dst *NotifyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyMessage.Merge(dst, src)
}
func (m *NotifyMessage) XXX_Size() int {
	return xxx_messageInfo_NotifyMessage.Size(m)
}
func (m *NotifyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyMessage proto.InternalMessageInfo

func (m *NotifyMessage) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *NotifyMessage) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *NotifyMessage) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NotifyMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *NotifyMessage) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *NotifyMessage) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type GetNotifyResponse struct {
	Notifications        []*NotifyMessage `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetNotifyResponse) Reset()         { *m = GetNotifyResponse{} }
func (m *GetNotifyResponse) String() string { return proto.CompactTextString(m) }
func (*GetNotifyResponse) ProtoMessage()    {}
func (*GetNotifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_notify_4ddc9a820ad42154, []int{1}
}
func (m *GetNotifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNotifyResponse.Unmarshal(m, b)
}
func (m *GetNotifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNotifyResponse.Marshal(b, m, deterministic)
}
func (dst *GetNotifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNotifyResponse.Merge(dst, src)
}
func (m *GetNotifyResponse) XXX_Size() int {
	return xxx_messageInfo_GetNotifyResponse.Size(m)
}
func (m *GetNotifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNotifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNotifyResponse proto.InternalMessageInfo

func (m *GetNotifyResponse) GetNotifications() []*NotifyMessage {
	if m != nil {
		return m.Notifications
	}
	return nil
}

type GetNotifyRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNotifyRequest) Reset()         { *m = GetNotifyRequest{} }
func (m *GetNotifyRequest) String() string { return proto.CompactTextString(m) }
func (*GetNotifyRequest) ProtoMessage()    {}
func (*GetNotifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_notify_4ddc9a820ad42154, []int{2}
}
func (m *GetNotifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNotifyRequest.Unmarshal(m, b)
}
func (m *GetNotifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNotifyRequest.Marshal(b, m, deterministic)
}
func (dst *GetNotifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNotifyRequest.Merge(dst, src)
}
func (m *GetNotifyRequest) XXX_Size() int {
	return xxx_messageInfo_GetNotifyRequest.Size(m)
}
func (m *GetNotifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNotifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNotifyRequest proto.InternalMessageInfo

func (m *GetNotifyRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetNotifyRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type UserToken struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserToken) Reset()         { *m = UserToken{} }
func (m *UserToken) String() string { return proto.CompactTextString(m) }
func (*UserToken) ProtoMessage()    {}
func (*UserToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_notify_4ddc9a820ad42154, []int{3}
}
func (m *UserToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserToken.Unmarshal(m, b)
}
func (m *UserToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserToken.Marshal(b, m, deterministic)
}
func (dst *UserToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToken.Merge(dst, src)
}
func (m *UserToken) XXX_Size() int {
	return xxx_messageInfo_UserToken.Size(m)
}
func (m *UserToken) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToken.DiscardUnknown(m)
}

var xxx_messageInfo_UserToken proto.InternalMessageInfo

func (m *UserToken) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RegisterTokenToTopicRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterTokenToTopicRequest) Reset()         { *m = RegisterTokenToTopicRequest{} }
func (m *RegisterTokenToTopicRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterTokenToTopicRequest) ProtoMessage()    {}
func (*RegisterTokenToTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_notify_4ddc9a820ad42154, []int{4}
}
func (m *RegisterTokenToTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterTokenToTopicRequest.Unmarshal(m, b)
}
func (m *RegisterTokenToTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterTokenToTopicRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterTokenToTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterTokenToTopicRequest.Merge(dst, src)
}
func (m *RegisterTokenToTopicRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterTokenToTopicRequest.Size(m)
}
func (m *RegisterTokenToTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterTokenToTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterTokenToTopicRequest proto.InternalMessageInfo

func (m *RegisterTokenToTopicRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *RegisterTokenToTopicRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type AddUserTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserTokenReq) Reset()         { *m = AddUserTokenReq{} }
func (m *AddUserTokenReq) String() string { return proto.CompactTextString(m) }
func (*AddUserTokenReq) ProtoMessage()    {}
func (*AddUserTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_notify_4ddc9a820ad42154, []int{5}
}
func (m *AddUserTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserTokenReq.Unmarshal(m, b)
}
func (m *AddUserTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserTokenReq.Marshal(b, m, deterministic)
}
func (dst *AddUserTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserTokenReq.Merge(dst, src)
}
func (m *AddUserTokenReq) XXX_Size() int {
	return xxx_messageInfo_AddUserTokenReq.Size(m)
}
func (m *AddUserTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserTokenReq proto.InternalMessageInfo

func (m *AddUserTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AddUserTokenResp struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserTokenResp) Reset()         { *m = AddUserTokenResp{} }
func (m *AddUserTokenResp) String() string { return proto.CompactTextString(m) }
func (*AddUserTokenResp) ProtoMessage()    {}
func (*AddUserTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_notify_4ddc9a820ad42154, []int{6}
}
func (m *AddUserTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserTokenResp.Unmarshal(m, b)
}
func (m *AddUserTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserTokenResp.Marshal(b, m, deterministic)
}
func (dst *AddUserTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserTokenResp.Merge(dst, src)
}
func (m *AddUserTokenResp) XXX_Size() int {
	return xxx_messageInfo_AddUserTokenResp.Size(m)
}
func (m *AddUserTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserTokenResp proto.InternalMessageInfo

func (m *AddUserTokenResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type PushNotifyReq struct {
	Notification         *NotifyMessage `protobuf:"bytes,1,opt,name=Notification,proto3" json:"Notification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PushNotifyReq) Reset()         { *m = PushNotifyReq{} }
func (m *PushNotifyReq) String() string { return proto.CompactTextString(m) }
func (*PushNotifyReq) ProtoMessage()    {}
func (*PushNotifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_notify_4ddc9a820ad42154, []int{7}
}
func (m *PushNotifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushNotifyReq.Unmarshal(m, b)
}
func (m *PushNotifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushNotifyReq.Marshal(b, m, deterministic)
}
func (dst *PushNotifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushNotifyReq.Merge(dst, src)
}
func (m *PushNotifyReq) XXX_Size() int {
	return xxx_messageInfo_PushNotifyReq.Size(m)
}
func (m *PushNotifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushNotifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushNotifyReq proto.InternalMessageInfo

func (m *PushNotifyReq) GetNotification() *NotifyMessage {
	if m != nil {
		return m.Notification
	}
	return nil
}

type PushNotifyResp struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushNotifyResp) Reset()         { *m = PushNotifyResp{} }
func (m *PushNotifyResp) String() string { return proto.CompactTextString(m) }
func (*PushNotifyResp) ProtoMessage()    {}
func (*PushNotifyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_notify_4ddc9a820ad42154, []int{8}
}
func (m *PushNotifyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushNotifyResp.Unmarshal(m, b)
}
func (m *PushNotifyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushNotifyResp.Marshal(b, m, deterministic)
}
func (dst *PushNotifyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushNotifyResp.Merge(dst, src)
}
func (m *PushNotifyResp) XXX_Size() int {
	return xxx_messageInfo_PushNotifyResp.Size(m)
}
func (m *PushNotifyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PushNotifyResp.DiscardUnknown(m)
}

var xxx_messageInfo_PushNotifyResp proto.InternalMessageInfo

func (m *PushNotifyResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*NotifyMessage)(nil), "grpcproto.notifyMessage")
	proto.RegisterType((*GetNotifyResponse)(nil), "grpcproto.getNotifyResponse")
	proto.RegisterType((*GetNotifyRequest)(nil), "grpcproto.getNotifyRequest")
	proto.RegisterType((*UserToken)(nil), "grpcproto.UserToken")
	proto.RegisterType((*RegisterTokenToTopicRequest)(nil), "grpcproto.RegisterTokenToTopicRequest")
	proto.RegisterType((*AddUserTokenReq)(nil), "grpcproto.AddUserTokenReq")
	proto.RegisterType((*AddUserTokenResp)(nil), "grpcproto.AddUserTokenResp")
	proto.RegisterType((*PushNotifyReq)(nil), "grpcproto.PushNotifyReq")
	proto.RegisterType((*PushNotifyResp)(nil), "grpcproto.PushNotifyResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotifyClient is the client API for Notify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotifyClient interface {
	GetNotify(ctx context.Context, in *GetNotifyRequest, opts ...grpc.CallOption) (*GetNotifyResponse, error)
	AddUserToken(ctx context.Context, in *AddUserTokenReq, opts ...grpc.CallOption) (*AddUserTokenResp, error)
	PushNotify(ctx context.Context, in *PushNotifyReq, opts ...grpc.CallOption) (*PushNotifyResp, error)
	RegisterTokenToTopic(ctx context.Context, in *RegisterTokenToTopicRequest, opts ...grpc.CallOption) (*Bool, error)
	UnRegisterTokenToTopic(ctx context.Context, in *RegisterTokenToTopicRequest, opts ...grpc.CallOption) (*Bool, error)
}

type notifyClient struct {
	cc *grpc.ClientConn
}

func NewNotifyClient(cc *grpc.ClientConn) NotifyClient {
	return &notifyClient{cc}
}

func (c *notifyClient) GetNotify(ctx context.Context, in *GetNotifyRequest, opts ...grpc.CallOption) (*GetNotifyResponse, error) {
	out := new(GetNotifyResponse)
	err := c.cc.Invoke(ctx, "/grpcproto.notify/getNotify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyClient) AddUserToken(ctx context.Context, in *AddUserTokenReq, opts ...grpc.CallOption) (*AddUserTokenResp, error) {
	out := new(AddUserTokenResp)
	err := c.cc.Invoke(ctx, "/grpcproto.notify/AddUserToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyClient) PushNotify(ctx context.Context, in *PushNotifyReq, opts ...grpc.CallOption) (*PushNotifyResp, error) {
	out := new(PushNotifyResp)
	err := c.cc.Invoke(ctx, "/grpcproto.notify/PushNotify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyClient) RegisterTokenToTopic(ctx context.Context, in *RegisterTokenToTopicRequest, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/grpcproto.notify/RegisterTokenToTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyClient) UnRegisterTokenToTopic(ctx context.Context, in *RegisterTokenToTopicRequest, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/grpcproto.notify/UnRegisterTokenToTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifyServer is the server API for Notify service.
type NotifyServer interface {
	GetNotify(context.Context, *GetNotifyRequest) (*GetNotifyResponse, error)
	AddUserToken(context.Context, *AddUserTokenReq) (*AddUserTokenResp, error)
	PushNotify(context.Context, *PushNotifyReq) (*PushNotifyResp, error)
	RegisterTokenToTopic(context.Context, *RegisterTokenToTopicRequest) (*Bool, error)
	UnRegisterTokenToTopic(context.Context, *RegisterTokenToTopicRequest) (*Bool, error)
}

func RegisterNotifyServer(s *grpc.Server, srv NotifyServer) {
	s.RegisterService(&_Notify_serviceDesc, srv)
}

func _Notify_GetNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServer).GetNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcproto.notify/GetNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServer).GetNotify(ctx, req.(*GetNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notify_AddUserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServer).AddUserToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcproto.notify/AddUserToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServer).AddUserToken(ctx, req.(*AddUserTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notify_PushNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushNotifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServer).PushNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcproto.notify/PushNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServer).PushNotify(ctx, req.(*PushNotifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notify_RegisterTokenToTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTokenToTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServer).RegisterTokenToTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcproto.notify/RegisterTokenToTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServer).RegisterTokenToTopic(ctx, req.(*RegisterTokenToTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notify_UnRegisterTokenToTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTokenToTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServer).UnRegisterTokenToTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcproto.notify/UnRegisterTokenToTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServer).UnRegisterTokenToTopic(ctx, req.(*RegisterTokenToTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notify_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcproto.notify",
	HandlerType: (*NotifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getNotify",
			Handler:    _Notify_GetNotify_Handler,
		},
		{
			MethodName: "AddUserToken",
			Handler:    _Notify_AddUserToken_Handler,
		},
		{
			MethodName: "PushNotify",
			Handler:    _Notify_PushNotify_Handler,
		},
		{
			MethodName: "RegisterTokenToTopic",
			Handler:    _Notify_RegisterTokenToTopic_Handler,
		},
		{
			MethodName: "UnRegisterTokenToTopic",
			Handler:    _Notify_UnRegisterTokenToTopic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notify.proto",
}

func init() { proto.RegisterFile("notify.proto", fileDescriptor_notify_4ddc9a820ad42154) }

var fileDescriptor_notify_4ddc9a820ad42154 = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0xd5, 0x36, 0x4d, 0xd0, 0x4e, 0x13, 0x5a, 0x46, 0x55, 0x65, 0x36, 0x1c, 0x22, 0x0b, 0x95,
	0x9c, 0x72, 0x28, 0x27, 0x24, 0x84, 0xa8, 0x40, 0x20, 0x84, 0x5a, 0xc0, 0x6c, 0x3e, 0x20, 0xdd,
	0x9d, 0x2c, 0x16, 0xd9, 0xf5, 0x76, 0xed, 0x1c, 0xb8, 0xf1, 0x33, 0xfc, 0x27, 0xb2, 0xbd, 0x6c,
	0xbd, 0x55, 0x9a, 0x13, 0x37, 0x3f, 0xfb, 0xcd, 0x9b, 0x79, 0x6f, 0x0c, 0xe3, 0x4a, 0x19, 0xb9,
	0xfe, 0xb5, 0xa8, 0x1b, 0x65, 0x14, 0xc6, 0x45, 0x53, 0x67, 0xee, 0x98, 0x8c, 0x33, 0x55, 0x96,
	0xaa, 0xf2, 0x0f, 0xfc, 0x4f, 0x04, 0x13, 0xcf, 0xbc, 0x22, 0xad, 0x57, 0x05, 0xe1, 0x19, 0x8c,
	0xb6, 0x9a, 0x9a, 0x4f, 0xef, 0x59, 0x34, 0x8b, 0xe6, 0xb1, 0x68, 0x11, 0xce, 0xe0, 0x28, 0x6b,
	0x68, 0x65, 0x28, 0x4f, 0x65, 0x49, 0xec, 0x60, 0x16, 0xcd, 0x07, 0x22, 0xbc, 0xc2, 0x53, 0x18,
	0x1a, 0x69, 0x36, 0xc4, 0x06, 0xae, 0xd0, 0x03, 0x64, 0xf0, 0xa8, 0xf4, 0xd2, 0xec, 0xd0, 0xdd,
	0xff, 0x83, 0x96, 0x2f, 0x4b, 0x7b, 0x3f, 0xf4, 0x7c, 0x07, 0x9c, 0x8a, 0xaa, 0x65, 0xc6, 0x46,
	0xad, 0x8a, 0x05, 0xfc, 0x3b, 0x3c, 0x29, 0xc8, 0x5c, 0xbb, 0x49, 0x05, 0xe9, 0x5a, 0x55, 0x9a,
	0xf0, 0x4d, 0x3b, 0xbb, 0xcc, 0x56, 0x46, 0xaa, 0x4a, 0xb3, 0x68, 0x36, 0x98, 0x1f, 0x5d, 0xb0,
	0x45, 0xe7, 0x76, 0xd1, 0xf3, 0x26, 0xfa, 0x74, 0xfe, 0x16, 0x4e, 0x02, 0xd1, 0xdb, 0x2d, 0x69,
	0x63, 0xdb, 0x6f, 0x64, 0x29, 0x8d, 0x73, 0x3f, 0x14, 0x1e, 0xd8, 0x50, 0xd4, 0x7a, 0xad, 0xc9,
	0x38, 0xdf, 0x43, 0xd1, 0x22, 0xfe, 0x0a, 0xe2, 0xa5, 0xa6, 0x26, 0x55, 0x3f, 0xa9, 0xb2, 0xa4,
	0x65, 0x2f, 0x39, 0x8f, 0xac, 0xa4, 0x23, 0xb8, 0xda, 0x58, 0x78, 0xc0, 0x3f, 0xc3, 0x54, 0x50,
	0x21, 0xb5, 0x69, 0xcb, 0x53, 0x95, 0x5a, 0xa7, 0xc1, 0x1c, 0x3e, 0x86, 0x28, 0x88, 0x21, 0x58,
	0xce, 0x41, 0xb8, 0x1c, 0xfe, 0x02, 0x8e, 0x2f, 0xf3, 0xbc, 0x1b, 0x45, 0xd0, 0xed, 0x5d, 0xd7,
	0x28, 0xec, 0x7a, 0x0e, 0x27, 0x7d, 0xa2, 0xae, 0x11, 0xe1, 0xf0, 0x9d, 0xca, 0xc9, 0x11, 0x27,
	0xc2, 0x9d, 0xf9, 0x15, 0x4c, 0xbe, 0x6e, 0xf5, 0x8f, 0x2e, 0x1b, 0x7c, 0x0d, 0xe3, 0xeb, 0x20,
	0x3c, 0x47, 0xde, 0x17, 0x75, 0x8f, 0xcd, 0x9f, 0xc3, 0xe3, 0x50, 0x6e, 0x77, 0xd3, 0x8b, 0xdf,
	0x03, 0x18, 0x79, 0x15, 0xfc, 0x00, 0x71, 0xb7, 0x1a, 0x9c, 0x06, 0x5d, 0xee, 0x2f, 0x2c, 0x79,
	0xb6, 0xfb, 0xb1, 0xfd, 0x22, 0x1f, 0x61, 0x1c, 0xfa, 0xc5, 0x24, 0x60, 0xdf, 0x4b, 0x2c, 0x99,
	0x3e, 0xf8, 0xa6, 0x6b, 0xbc, 0x04, 0xb8, 0x73, 0x80, 0xa1, 0xef, 0x5e, 0x4e, 0xc9, 0xd3, 0x07,
	0x5e, 0x74, 0x8d, 0x5f, 0xe0, 0x74, 0xd7, 0xc6, 0xf1, 0x3c, 0x28, 0xd9, 0xf3, 0x25, 0x92, 0xe3,
	0x80, 0x77, 0xa3, 0xd4, 0x06, 0xbf, 0xc1, 0xd9, 0xb2, 0xfa, 0xaf, 0x92, 0x37, 0x23, 0x77, 0x7e,
	0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0x68, 0x3a, 0x9c, 0x93, 0x3f, 0x04, 0x00, 0x00,
}
