// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notify.proto

package grpcproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NotifyMessage struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	CreatedTime          int64    `protobuf:"varint,2,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyMessage) Reset()         { *m = NotifyMessage{} }
func (m *NotifyMessage) String() string { return proto.CompactTextString(m) }
func (*NotifyMessage) ProtoMessage()    {}
func (*NotifyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_notify_fe3cb471fd7ff584, []int{0}
}
func (m *NotifyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyMessage.Unmarshal(m, b)
}
func (m *NotifyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyMessage.Marshal(b, m, deterministic)
}
func (dst *NotifyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyMessage.Merge(dst, src)
}
func (m *NotifyMessage) XXX_Size() int {
	return xxx_messageInfo_NotifyMessage.Size(m)
}
func (m *NotifyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyMessage proto.InternalMessageInfo

func (m *NotifyMessage) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *NotifyMessage) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *NotifyMessage) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NotifyMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetNotifyRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNotifyRequest) Reset()         { *m = GetNotifyRequest{} }
func (m *GetNotifyRequest) String() string { return proto.CompactTextString(m) }
func (*GetNotifyRequest) ProtoMessage()    {}
func (*GetNotifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_notify_fe3cb471fd7ff584, []int{1}
}
func (m *GetNotifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNotifyRequest.Unmarshal(m, b)
}
func (m *GetNotifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNotifyRequest.Marshal(b, m, deterministic)
}
func (dst *GetNotifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNotifyRequest.Merge(dst, src)
}
func (m *GetNotifyRequest) XXX_Size() int {
	return xxx_messageInfo_GetNotifyRequest.Size(m)
}
func (m *GetNotifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNotifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNotifyRequest proto.InternalMessageInfo

func (m *GetNotifyRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetNotifyRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func init() {
	proto.RegisterType((*NotifyMessage)(nil), "grpcproto.notifyMessage")
	proto.RegisterType((*GetNotifyRequest)(nil), "grpcproto.getNotifyRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotifyClient is the client API for Notify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotifyClient interface {
	GetNotify(ctx context.Context, in *GetNotifyRequest, opts ...grpc.CallOption) (*NotifyMessage, error)
}

type notifyClient struct {
	cc *grpc.ClientConn
}

func NewNotifyClient(cc *grpc.ClientConn) NotifyClient {
	return &notifyClient{cc}
}

func (c *notifyClient) GetNotify(ctx context.Context, in *GetNotifyRequest, opts ...grpc.CallOption) (*NotifyMessage, error) {
	out := new(NotifyMessage)
	err := c.cc.Invoke(ctx, "/grpcproto.notify/getNotify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifyServer is the server API for Notify service.
type NotifyServer interface {
	GetNotify(context.Context, *GetNotifyRequest) (*NotifyMessage, error)
}

func RegisterNotifyServer(s *grpc.Server, srv NotifyServer) {
	s.RegisterService(&_Notify_serviceDesc, srv)
}

func _Notify_GetNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServer).GetNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcproto.notify/GetNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServer).GetNotify(ctx, req.(*GetNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notify_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcproto.notify",
	HandlerType: (*NotifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getNotify",
			Handler:    _Notify_GetNotify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notify.proto",
}

func init() { proto.RegisterFile("notify.proto", fileDescriptor_notify_fe3cb471fd7ff584) }

var fileDescriptor_notify_fe3cb471fd7ff584 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcb, 0x2f, 0xc9,
	0x4c, 0xab, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0x2f, 0x2a, 0x48, 0x06, 0x33,
	0x95, 0x2a, 0xb9, 0x78, 0x21, 0x52, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x42, 0x62, 0x5c,
	0x6c, 0xa5, 0xc5, 0xa9, 0x45, 0x9e, 0x2e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x9e,
	0x90, 0x02, 0x17, 0x77, 0x72, 0x51, 0x6a, 0x62, 0x49, 0x6a, 0x4a, 0x48, 0x66, 0x6e, 0xaa, 0x04,
	0x93, 0x02, 0xa3, 0x06, 0x73, 0x10, 0xb2, 0x90, 0x90, 0x08, 0x17, 0x6b, 0x49, 0x66, 0x49, 0x4e,
	0xaa, 0x04, 0x33, 0x58, 0x23, 0x84, 0x23, 0x24, 0xc1, 0xc5, 0x9e, 0x0b, 0x31, 0x5a, 0x82, 0x05,
	0x2c, 0x0e, 0xe3, 0x2a, 0x39, 0x70, 0x09, 0xa4, 0xa7, 0x96, 0xf8, 0x81, 0x6d, 0x0f, 0x4a, 0x2d,
	0x2c, 0x4d, 0x2d, 0x2e, 0x01, 0x99, 0x91, 0x93, 0x99, 0x9b, 0x59, 0x02, 0xb6, 0x9c, 0x35, 0x08,
	0xc2, 0x01, 0xb9, 0x29, 0x3f, 0x2d, 0xad, 0x38, 0xb5, 0x04, 0x6c, 0x2d, 0x6b, 0x10, 0x94, 0x67,
	0xe4, 0xc3, 0xc5, 0x06, 0x71, 0xbc, 0x90, 0x13, 0x17, 0x27, 0xdc, 0x2c, 0x21, 0x69, 0x3d, 0xb8,
	0xff, 0xf4, 0xd0, 0x6d, 0x90, 0x92, 0x40, 0x92, 0x44, 0xf1, 0x79, 0x12, 0x1b, 0x58, 0xd0, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x9f, 0x2c, 0x6a, 0x2c, 0x01, 0x00, 0x00,
}
